name: 'Generate Context File'
description: 'Generate OpenContext Artifact Context File'
inputs:
  type:
    description: 'Type of artifact. One of sbom, container, package, or image'
    required: true
  url:
    description: 'URL/URI of the artifact'
    required: true
  directory:
    description: 'Directory to save YAML files to. If not specified then the directory oc-artifact-yaml will be used.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.artifact-type }}
    - ${{ inputs.url }}
