apiVersion: opencontext.com/v1alpha1
kind: CodeComponent
metadata:
  namespace: GH_ORG
  name: ARTIFACT_NAME
  title: ARTIFACT_LONG_NAME
  links:
    - url: ARTIFACT_URL
      title: ARTIFACT_NAME
    - url: GITHUB_ACTION_URL
      title: GitHub Actions Run
  annotations:
    github.com/project-slug: GITHUB_REPO
spec:
  type: ARTIFACT_TYPE
  uri: ARTIFACT_URL
  owner: []
  dependsOn: []
